server:
  port: 8088

spring:
  datasource:
    driver-class-name: ${DB_CLASS}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: 'true'

  data:
    redis:
      host: ${R_HOST}
      port: ${R_PORT}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  accessTime: ${ACCESS_TIME}
  refreshTime: ${REFRESH_TIME}

